services:
  postgres:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=cassierq'
      - 'POSTGRES_USER=cassierq'
      - 'POSTGRES_PASSWORD=cassierq'
    ports:
      - '5432:5432'
    volumes:
      - cassierq_api_postgres_data:/var/lib/postgresql/data

volumes:
  cassierq_api_postgres_data:
